info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: http://configuration:8788/scm/git/dbs.git
          username: configserver
          password: j81tMvd3zG71h850768dh4VL256B37SL
          repos:
             data-config:
                 uri: http://configuration:8788/scm/git/dbs-data.git
                 username: configserver
                 password: j81tMvd3zG71h850768dh4VL256B37SL
                 pattern: "*_data_*"
server:
  port: 8888
management:
  context_path: /admin
